# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ae433fdaa297689e55a274894e287f18def8c348e5d741227f396c047ff1ad1ca70509998eefe98c8734615e6e81c585d2ac840895a780edd07c73b3c39d616

test:
  secret_key_base: 52410dd155bd0b3e4ea975711b2383fc94ce2a05dd7b980fa749a9e039117e50e52a1ec73113d467fdf15fefe2faf37c85249438fc3de074813406d0a4954396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
